codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: false

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
