services:
  postgres:
    image: postgres:16-alpine
    container_name: aw-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 60
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
