name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.6-dind
        options: >-
          --privileged=true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install deps (with all connectors)
        run: |
          # Install project with dev deps and all optional connectors to avoid skipped tests
          poetry install --no-interaction --with dev -E connectors-all

      - name: Make wait script executable
        run: chmod +x test_helpers/wait-for-postgres.sh

      - name: Start services via Docker Compose
        run: docker compose -f test_helpers/docker-compose.yml up -d

      - name: Wait for Postgres
        run: ./test_helpers/wait-for-postgres.sh 127.0.0.1 5432

      - name: Set DSN
        run: echo "AUTO_WORKFLOW_CONNECTORS_POSTGRES_EXAMPLE__DSN=postgresql://postgres:postgres@127.0.0.1:5432/postgres" >> $GITHUB_ENV

      - name: Lint / Docs / Tests
        run: |
          set -euo pipefail
          poetry run ruff format --check .
          poetry run ruff check .
          poetry run mkdocs build --strict
          poetry run pytest -q --disable-warnings --maxfail=1 --cov=auto_workflow --cov-branch --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true

      - name: Stop services
        if: always()
        run: docker compose -f test_helpers/docker-compose.yml down -v
